In [1]:
# 数据的导入
import pandas as pd
df = pd.read_csv('data/employees.csv',encoding='utf-8')
print(df.salary.mean())
# 数据的导出
df = df.tail(10)
df.to_csv('output/employees_tail.csv')

6461.682242990654

In [2]:
# json数据  做爬虫会用到
df = pd.read_json('data/test.json')
print(type(df))
df  # 显示json数据，但是识别会有问题，字段识别不正常

import json
with open('data/test.json',encoding='utf-8') as f:
    data = json.load(f)
print(data)
print(type(data))   # 字典
df = pd.DataFrame(data['users'])
df

<class 'pandas.DataFrame'>
{'users': [{'id': 1, 'name': '张三', 'age': 28, 'email': 'zhangsan@example.com', 'is_active': True, 'join_date': '2022-03-15'}, {'id': 2, 'name': '李四', 'age': 35, 'email': 'lisi@example.com', 'is_active': False, 'join_date': '2021-11-02'}, {'id': 3, 'name': '王五', 'age': 24, 'email': 'wangwu@example.com', 'is_active': True, 'join_date': '2023-01-20'}]}
<class 'dict'>

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [3]:
# 数据处理
# 缺失值的处理
import pandas as pd
import numpy as np
s = pd.Series([1,2,3,np.nan,5,None,pd.NA])  # 这三种都是缺失值
df = pd.DataFrame([[1,2,3],[4,np.nan,6],[7,None,pd.NA]], columns=['第一列','第二列','第三列'])  # 这三种都是缺失值
print(s)
print(df)
# 查看是否是缺失值
print(s.isna())  # True表示缺失值
print(s.isnull())  # True表示缺失值
print(df.isna())
print(df.isnull())
print(s.isna().sum())  # 缺失值的数量
print(df.isna().sum())  # 缺失值的数量

0       1
1       2
2       3
3     NaN
4       5
5    None
6    <NA>
dtype: object
   第一列  第二列   第三列
0    1  2.0     3
1    4  NaN     6
2    7  NaN  <NA>
0    False
1    False
2    False
3     True
4    False
5     True
6     True
dtype: bool
0    False
1    False
2    False
3     True
4    False
5     True
6     True
dtype: bool
     第一列    第二列    第三列
0  False  False  False
1  False   True  False
2  False   True   True
     第一列    第二列    第三列
0  False  False  False
1  False   True  False
2  False   True   True
3
第一列    0
第二列    2
第三列    1
dtype: int64

In [4]:
# 剔除缺失值
print(s.dropna())
print(df)
print(df.dropna())  # 一行内有缺失值，整行会被剔除
print(df.dropna(how='all'))  # 一行内全是缺失值，整行会被剔除
print(df.dropna(thresh=2))  # 至少有2个非缺失值，整行才会保留
print(df.dropna(axis=1))  # 一列内有缺失值，整列会被剔除
print(df.dropna(subset=['第二列']))  # 如果某列有缺失值，则那一行会被剔除

0    1
1    2
2    3
4    5
dtype: object
   第一列  第二列   第三列
0    1  2.0     3
1    4  NaN     6
2    7  NaN  <NA>
   第一列  第二列 第三列
0    1  2.0   3
   第一列  第二列   第三列
0    1  2.0     3
1    4  NaN     6
2    7  NaN  <NA>
   第一列  第二列 第三列
0    1  2.0   3
1    4  NaN   6
   第一列
0    1
1    4
2    7
   第一列  第二列 第三列
0    1  2.0   3

In [5]:
# 填充缺失值
df = pd.read_csv('data/weather_withna.csv',encoding='utf-8')
print(df.isna().sum())  # 查看每列缺失值的数量
df.head()
# 使用固定值填充缺失值
print(df.fillna({'temp_max':20}).tail())  # 使用字典来填充
print(df.fillna(df[['wind']].mean().tail()))  # 用平均值填充缺失值
print(df.ffill().tail())  # 用前一个值填充缺失值
print(df.bfill().tail())  # 用后一个值填充缺失值

date               0
precipitation    303
temp_max         303
temp_min         303
wind             303
weather          303
dtype: int64
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind  weather
0     2012-01-01            0.0      12.8       5.0  4.700000  drizzle
1     2012-01-02           10.9      10.6       2.8  4.500000     rain
2     2012-01-03            0.8      11.7       7.2  2.300000     rain
3     2012-01-04           20.3      12.2       5.6  4.700000     rain
4     2012-01-05            1.3       8.9       2.8  6.100000     rain
...          ...            ...       ...       ...       ...      ...
1456  2015-12-27            NaN       NaN       NaN  3.242055      NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055      NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055      NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055      NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000     rain

[1461 rows x 6 columns]
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [6]:
# 数据类型转换
data = {
    "name": ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    "age": [26, 25, 30, 25, 35, 30],
    "city": ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)

In [7]:
df.duplicated()  # 一整条记录都是一样的，标记为重复，返回True
df.drop_duplicates()  # 删除重复的记录，保留第一条
df.drop_duplicates(subset=['name'])  # 根据指定的列去重
df.drop_duplicates(subset=['name'],keep='last')  # 根据指定的列去重，以最新的数据为准

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [8]:
# 数据类型的转换
df = pd.read_csv('data/sleep.csv',encoding='utf-8')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [9]:
df['age'] = df['age'].astype('int16')  # 转换为整数类型
df.dtypes
df.gender = df.gender.astype('category')  # 转换为分类类型

In [10]:
df['is_male'] = df['gender'].map({'Female':False,'Male':True})  # 转换为布尔类型

In [11]:
# 数据变形
import pandas as pd
data = {
    'ID': [1, 2],
    'name': ['alice', 'bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
df
'''
1 alice math 90
1 alice english 88
1 alice science 95
2 bob math 85
2 bob english 92
2 bob science 89
'''
# 宽表转换成长表    id_vars: 固定的列，不转换为长表  var_name: 转换后的列名
# value_name: 转换后的值列名
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values(by=['name'],inplace=True)
df2

# 长表转宽表
pd.pivot(df2,index=['ID','name'],columns='科目',values='分数')  # reset_index() 重置索引

科目        English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89

In [12]:
data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob jones'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89]
}
df = pd.DataFrame(data)
# 分列
df[['first_name','last_name']] = df['name'].str.split(' ',expand=True)  # expand=True 分列，返回DataFrame  expand=False 分列，返回Series
df = pd.read_csv('data/sleep.csv',encoding='utf-8')
df.head()
df[['person_id','blood_pressure']]
df[['高压','低压']] = df['blood_pressure'].str.split('/',expand=True)  # 分列
df[['高压','低压']] = df[['高压','低压']].astype('int16')  # 转换为整数类型
df[['高压','低压']].dtypes

高压    int16
低压    int16
dtype: object

In [13]:
# 数据分箱  pd.cut(x,bins,labels)  # 分箱，返回分箱的区间
# x: 要分箱的列
# bins: 分箱的区间
# labels: 分箱的标签
import pandas as pd
df = pd.read_csv('data/employees.csv',encoding='utf-8')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [14]:
df1 = df.head(10)[['employee_id','salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [15]:
pd.cut(df1.salary,bins=2)   # bins=n，分成n段区间，起始值和结束值是所有数据的最小值和最大值
# 4180.2 - 14100.0 - 24000.0
pd.cut(df1.salary,bins=3).value_counts()  # 查看每个区间的数量
pd.cut(df1.salary,bins=[0,10000,20000,30000]).value_counts()   # bins=list，指定分箱的区间
# 0 - 10000 - 20000 - 30000
df1['收入范围'] = pd.cut(df1.salary,bins=[0,10000,20000,30000],labels=['低','中','高'])    # labels=list，指定每个区间的标签
pd.qcut(df1.salary,3).value_counts()   # qcut: 分位数分箱，q=n，分成n段区间

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [16]:
# 睡眠数据
df = pd.read_csv('data/sleep.csv',encoding='utf-8')
df['睡眠质量等级'] = pd.qcut(df.sleep_quality,3,labels=['睡眠质量低','睡眠质量中','睡眠质量高'])
df['睡眠质量等级'] = pd.cut(df.sleep_quality,bins=3,labels=['睡眠质量低','睡眠质量中','睡眠质量高'])
df['睡眠质量等级'].value_counts()

睡眠质量等级
睡眠质量中    206
睡眠质量高    129
睡眠质量低     65
Name: count, dtype: int64

In [17]:
# 字符串 --> 类别 --> 统计
# 数值 --> 分箱 --> 统计

In [18]:
# df.rename()   df.set_index()  df.reset_index()
df = pd.DataFrame(
    {
        'name':['jack','jill','james','jane','james'],
        'age':[20,21,22,23,24],
        'gender':['male','female','male','female','male']
    }
)
df.set_index('name',inplace=True)
df.reset_index(inplace=True)
df.rename(columns={'age':'年龄'},inplace=True)
df

    name  年龄  gender
0   jack  20    male
1   jill  21  female
2  james  22    male
3   jane  23  female
4  james  24    male

In [19]:
df.index=[1,2,3,4,5]
df.columns=['姓名','年龄','性别']
df

      姓名  年龄      性别
1   jack  20    male
2   jill  21  female
3  james  22    male
4   jane  23  female
5  james  24    male

In [20]:
# 时间数据的处理
d = pd.Timestamp('2015-05-31 10:22:00')
print(d)
print(type(d))
print(f"d.year = {d.year}")
print(f"d.month = {d.month}")
print(f"d.day = {d.day}")
print(f"d.hour = {d.hour}")
print(f"d.minute = {d.minute}")
print(f"d.second = {d.second}")
print(f"季度：{d.quarter}")
print(f"星期：{d.weekday()}")
print(f"是否是月底：{d.is_month_end}")

# 方法
print(f"星期几：{d.day_name()}")
print(f"转换为天：{d.to_period('D')}")
print(f"转换为季度：{d.to_period('Q')}")
print(f"转换为年度：{d.to_period('Y')}")
print(f"转换为月度：{d.to_period('M')}")
print(f"转换为周：{d.to_period('W')}")

2015-05-31 10:22:00
<class 'pandas.Timestamp'>
d.year = 2015
d.month = 5
d.day = 31
d.hour = 10
d.minute = 22
d.second = 0
季度：2
星期：6
是否是月底：True
星期几：Sunday
转换为天：2015-05-31
转换为季度：2015Q2
转换为年度：2015
转换为月度：2015-05
转换为周：2015-05-25/2015-05-31

In [21]:
# 字符串转化成日期类型
a = pd.to_datetime('2015-02-28 10:22:00')
print(a)
print(type(a))
print(a.day_name())

# dataFrame 日期转换
df = pd.DataFrame(
    {
        'sales': [100, 200, 300],
        'date': ['20150101', '20150102', '20150103']
    }
)
df['datatime'] = pd.to_datetime(df['date'])
print(df)
print(df['datatime'])
print(df['datatime'].dt.year)
print(df['datatime'].dt.month)
print(df['datatime'].dt.day)
print(df['datatime'].dt.day_name())

2015-02-28 10:22:00
<class 'pandas.Timestamp'>
Saturday
   sales      date   datatime
0    100  20150101 2015-01-01
1    200  20150102 2015-01-02
2    300  20150103 2015-01-03
0   2015-01-01
1   2015-01-02
2   2015-01-03
Name: datatime, dtype: datetime64[us]
0    2015
1    2015
2    2015
Name: datatime, dtype: int32
0    1
1    1
2    1
Name: datatime, dtype: int32
0    1
1    2
2    3
Name: datatime, dtype: int32
0    Thursday
1      Friday
2    Saturday
Name: datatime, dtype: str

In [22]:
# csv 日期转换  parse_dates参数可以将指定的列转换为日期类型
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df.info()
df['datetime'] = pd.to_datetime(df['date'])
df['datetime'].dt.day_name()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

0          Sunday
1          Monday
2         Tuesday
3       Wednesday
4        Thursday
          ...
1456       Sunday
1457       Monday
1458      Tuesday
1459    Wednesday
1460     Thursday
Name: datetime, Length: 1461, dtype: str

In [23]:
# 日期数据作为索引  inplace=True设置原来的df的索引，直接生效的
# df.set_index('date',inplace=True)
print(df.loc['2013-01':'2013-02'])

Empty DataFrame
Columns: [date, precipitation, temp_max, temp_min, wind, weather, datetime]
Index: []

In [24]:
# 时间的间隔
d1 = pd.Timestamp('2023-01-15')
d2 = pd.Timestamp('2023-02-23')
d3 = d2 - d1
print(type(d3))
print(d3)
print(d3.days)

<class 'pandas.Timedelta'>
39 days 00:00:00
39

In [25]:
# delta 时间间隔的列   表示距离第一天过了多少天
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
df['delta'] = df['date'] - df['date'][0]
df.set_index('delta',inplace=True)
print(df.loc['10 days':'20 days'])

              date  precipitation  temp_max  temp_min  wind weather
delta
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun
11 days 2012-01-12            0.0       6.1      -1.7   1.9     sun
12 days 2012-01-13            0.0       5.0      -2.8   1.3     sun
13 days 2012-01-14            4.1       4.4       0.6   5.3    snow
14 days 2012-01-15            5.3       1.1      -3.3   3.2    snow
15 days 2012-01-16            2.5       1.7      -2.8   5.0    snow
16 days 2012-01-17            8.1       3.3       0.0   5.6    snow
17 days 2012-01-18           19.8       0.0      -2.8   5.0    snow
18 days 2012-01-19           15.2      -1.1      -2.8   1.6    snow
19 days 2012-01-20           13.5       7.2      -1.1   2.3    snow
20 days 2012-01-21            3.0       8.3       3.3   8.2    rain

In [26]:
# 生成日期范围
# freq='D' 表示每天 freq='W' 表示每周 freq='M' 表示每月 freq='Y' 表示每年 
# periods 表示生成的日期数量
days = pd.date_range(start='2023-01-15',end='2024-02-23',freq='W')
days = pd.date_range(start='2023-01-15',periods=10,freq='YS')
print(days)

DatetimeIndex(['2024-01-01', '2025-01-01', '2026-01-01', '2027-01-01',
               '2028-01-01', '2029-01-01', '2030-01-01', '2031-01-01',
               '2032-01-01', '2033-01-01'],
              dtype='datetime64[us]', freq='YS-JAN')

In [27]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
# 重新采样
df.set_index('date',inplace=True)

In [28]:
# 按年重新采样  表示按年重新采样，每个年份的温度最大值和最小值的平均值
df[['temp_max','temp_min']].resample('YE').mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [53]:
# 分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
import pandas as pd
df = pd.read_csv('data/employees.csv')
print(df['department_id'].isna().sum())
df.dropna(subset=['department_id'],inplace=True)
print(df['department_id'].isna().sum())
df['department_id'] = df['department_id'].astype('int16')
# 计算不同部门的平均薪资
print(df.groupby('department_id').groups)   # 显示每个部门的索引，查看分组
print(df.groupby('department_id').get_group(10))    # 查看具体某个分组数据
df2 =df.groupby('department_id')['salary'].mean().round(2)
df2 = df2.reset_index()
df2.sort_values('salary',ascending=False)

1
0
{10: [100], 20: [101, 102], 30: [14, 15, 16, 17, 18, 19], 40: [103], 50: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], 60: [3, 4, 5, 6, 7], 70: [104], 80: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 79], 90: [0, 1, 2], 100: [8, 9, 10, 11, 12, 13], 110: [105, 106]}
     employee_id first_name last_name    email  phone_number   job_id  salary  \
100          200   Jennifer    Whalen  JWHALEN  515.123.4444  AD_ASST  4400.0

     commission_pct  manager_id  department_id
100             NaN       101.0             10

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [64]:
# 计算不同部门不同岗位的人的平均薪资
df3 = df.groupby(['department_id','job_id'])['salary'].mean().round(2)  # 单层返回的是Series
df3 = df.groupby(['department_id','job_id'])[['salary']].mean().round(2)    # 双层返回的是DataFrame，列名是salary
df3 = df3.reset_index()
df3 = df3.sort_values('salary',ascending=False)
df3

    department_id      job_id    salary
13             90     AD_PRES  24000.00
14             90       AD_VP  17000.00
1              20      MK_MAN  13000.00
11             80      SA_MAN  12200.00
16            100      FI_MGR  12000.00
18            110      AC_MGR  12000.00
4              30      PU_MAN  11000.00
10             70      PR_REP  10000.00
12             80      SA_REP   8396.55
17            110  AC_ACCOUNT   8300.00
15            100  FI_ACCOUNT   7920.00
8              50      ST_MAN   7280.00
5              40      HR_REP   6500.00
2              20      MK_REP   6000.00
9              60     IT_PROG   5760.00
0              10     AD_ASST   4400.00
6              50    SH_CLERK   3215.00
7              50    ST_CLERK   2785.00
3              30    PU_CLERK   2780.00

In [ ]:
# 企鹅数据分析
# 1. 导入必要库
import pandas as pd
# 2. 导入数据
df = pd.read_csv('data/penguins.csv')
df.head(5)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [ ]:
# 3. 数据清洗
# 3.1 缺失值处理
print(df.isna().sum())
df.dropna(inplace=True)

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
# 4. 数据特征构造
df['sex'] = df['sex'].astype('category')
df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']

In [87]:
# 5. 数据分析
# 5.1 数据分箱-把体重分为低中高三个等级
labels = ['低','中','高']
df['mass_level'] = pd.cut(df['body_mass_g'],bins=3,labels=labels)
print(df['mass_level'].value_counts())
# 按岛屿，性别分组分析
# 只能算一种指标
# df.groupby('sex')['body_mass_g'].mean()
# agg可以一次性算多个指标：均值、数量、最大最小、标准差
# df.groupby('sex')['body_mass_g'].agg(['mean','count','max','min'])
df.groupby(['sex','island']).agg(
    {
        'body_mass_g':['mean','count']
    }
)

mass_level
低    150
中    128
高     55
Name: count, dtype: int64

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23

In [90]:
# 1. 导入库
import pandas as pd
import numpy as np
# 2. 导入数据
df = pd.read_csv('data/sleep.csv')
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    str
 2   age                      400 non-null    int64
 3   occupation               400 non-null    str
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    str
 9   blood_pressure           400 non-null    str
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    str
dtypes: float64(2), int64(6), str(5)
memory usage: 40.8 KB

,person_id,age,sleep_duration,sleep_quality,physical_activity_level,stress_level,heart_rate,daily_steps
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000
mean,200.500000,39.950000,8.041250,6.125750,64.985000,5.47250,75.990000,11076.510000
std,115.614301,14.038883,2.390787,1.975733,32.297874,2.80873,15.099334,5364.789364
min,1.000000,18.000000,4.100000,1.000000,10.000000,1.00000,50.000000,2067.000000
25%,100.750000,29.000000,5.900000,4.700000,35.000000,3.00000,63.000000,6165.250000
50%,200.500000,40.000000,8.200000,6.100000,65.500000,5.00000,77.000000,11785.500000
75%,300.250000,49.000000,10.125000,7.425000,94.000000,8.00000,90.000000,15878.000000
max,400.000000,90.000000,12.000000,10.000000,120.000000,10.00000,100.000000,19958.000000

In [94]:
# 3. 数据清洗
df.isna().sum()
df.drop(columns='sleep_disorder',inplace=True)

In [ ]:
# 4. 数据特征构造
df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')
df['bmi_category'] = df['bmi_category'].astype('category')
df[['high','low']] = df['blood_pressure'].str.split('/',expand=True)
# 睡眠质量的分箱
labels = ['差','中','优']
df['sleep_quality_level'] = pd.cut(df['sleep_quality'],bins=3,labels=labels)
age_labels = ['青年','中年','老年']
df['age_level'] = pd.cut(df['age'],bins=[0,30,60,120],labels=age_labels)

     age age_level
0     29        青年
1     43        中年
2     44        中年
3     29        青年
4     67        老年
..   ...       ...
395   36        中年
396   45        中年
397   30        青年
398   41        中年
399   37        中年

[400 rows x 2 columns]

In [116]:
# 5. 数据的统计与分析
print(df['bmi_category'].value_counts())

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

In [119]:
# 根据不同的bmi分组，睡眠质量
df.groupby(['age_level','bmi_category']).agg(
    {
        'sleep_duration':'mean',
        'sleep_quality':'mean',
        'stress_level':'mean'
    }
)

                        sleep_duration  sleep_quality  stress_level
age_level bmi_category
青年        Normal              8.184000       6.464000      5.200000
          Obese               7.861538       6.400000      5.807692
          Overweight          7.823077       5.703846      5.461538
          Underweight         7.190244       5.678049      5.146341
中年        Normal              7.748148       6.461111      4.870370
          Obese               8.192537       6.164179      5.611940
          Overweight          8.401449       6.188406      5.463768
          Underweight         8.453448       6.046552      5.862069
老年        Normal              7.191667       5.558333      4.083333
          Obese               7.560000       5.440000      7.600000
          Overweight          8.485714       6.414286      6.857143
          Underweight         9.700000       5.966667      5.333333